### ISSUE TITLE
Not startable

### ISSUE THREAD

**Issue by Ex3CuTioNx3** [GneHeHe/SmartRandomBuildGeneratorDbD#6]
I can't start the program. I also downloaded the old java but it still not start.

**Comment by GneHeHe** [comment]
Hello,
Have you tried installing Java SE Runtime Environment 9 ( "jre-9.0.4_windows-x64_bin.exe") ?
https://www.oracle.com/java/technologies/javase-java-archive-javase9-downloads.html
Let me know :)

**Comment by GneHeHe** [comment]
Hello,
Have you tried installing Java SE Runtime Environment ( "jre-8u261-windows-x64.exe") ?
https://www.oracle.com/java/technologies/javase-downloads.html
https://www.oracle.com/java/technologies/javase-jre8-downloads.html
Let me know :)

**Comment by Ex3CuTioNx3** [comment]
I tried all java versions you send to me. No one works for me. :(

**Comment by GneHeHe** [comment]
Ok, try this
http://prntscr.com/toj8cr
We should have access to the error message

Finally, what is the result of the command "java -version" in your shell (cmd.exe) ?

**Comment by GneHeHe** [comment]
I also made some quick tests on my old win7 laptop:

1) very old java version was present, so I started by remove it using the control panel

2) I search for "java download" on google.com and automatically downloaded a setup ( "jre-8u261-windows-x64.exe" ) from the "https://www.java.com" website

3) I installed it and rebooted my laptop

4) I was able to successfully run the current and previous versions from SRBG using both ways (command-line mode using "java -jar SRBG.jar" command or with the double click on the jar file)

**Comment by GneHeHe** [comment]
For information, a wrapped version (jar->exe) has been generated and uploaded on github
Its main purpose is to be more user-friendly than the jar-based launching of the tool
Recent JAVA still is required but everything else is handled on the fly just by double clicking on the EXE file

You can find the download URL on the homepage of this project

https://github.com/GneHeHe/SmartRandomBuildGeneratorDbD
