### ISSUE TITLE
Perk List Empty

### ISSUE THREAD

**Issue by Jofagi** [GneHeHe/SmartRandomBuildGeneratorDbD#7]
If I understand correctly, I should get a list of builds but instead I get this:
![image](https://user-images.githubusercontent.com/6442817/202549640-125ac0b0-9ea4-4e65-9205-85f67bb97ae6.png)

Any idea what could be the problem here?

I'm starting SRBG via `java --module-path .\openjfx-19_windows-x64_bin-sdk\javafx-sdk-19\lib\ --add-modules javafx.swing -jar .\SRBG.jar` using

```cmd
> java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```

My OS is Win11.

**Comment by GneHeHe** [comment]
Hi,

Indeed, you should see something like this:

![image](https://user-images.githubusercontent.com/47244555/203873765-1ab17f03-2493-4c80-a777-0bcc3e435c0e.png)

Do you have light grey / white colored text within the large text area?

**Comment by GneHeHe** [comment]
By the way, why do you use the OpenJDK on Win? Tool developed and tested with regular Oracle Java fyi.

**Comment by Jofagi** [comment]
I had the OpenJDK installed for other reasons already. It was quite an effort to get it running with `javafx.swing` which is apparently non-standard anymore and therefore is not part of OpenJDK. Or something like that.

Anyway thanks for the hint, now that I installed jre8, it works!
